import { IPlanesConfig } from 'assets/interfaces/IPlanesConfig';

export const AMX: IPlanesConfig = {
  id: 'amx',
  name: 'AMX-A1',
  initial_ammo: 30,
  ammo_upgrade: 60,
  max_ammo: 300,
  initial_missile: 2,
  max_missile: 6,
  speed: 180,
  max_speed: 210,
  fuel_consuption: 6.25,
  fuel_effiency: 3.75,
  fly_animation: 'amx_fly',
  engine_sound: 'jet_engine',
  muzzleFlash_X: 40,
  muzzleFlash_Y: 9.5,
  misssileAttached_X: -6,
  misssileAttached_Y: 5,
  main_gun_fire_X: 40,
  origin_X: 40,
  origin_Y: 300,
  name_menu_x: 500,
  menu_selection_weapons: 1,
  menu_selection_speed: 1,
  menu_selection_fuel: 1,
  menu_selection_sprite: 1,
};
