import { IPlanesConfig } from 'assets/interfaces/IPlanesConfig';

export const GRIPEN: IPlanesConfig = {
  id: 'gripen',
  name: 'F39-E Gripen',
  initial_ammo: 50,
  ammo_upgrade: 100,
  max_ammo: 120,
  initial_missile: 4,
  max_missile: 8,
  speed: 210,
  max_speed: 240,
  fuel_consuption: 7.5,
  fuel_effiency: 5,
  fly_animation: 'gripen_fly',
  engine_sound: 'jet_engine',
  muzzleFlash_X: 40,
  muzzleFlash_Y: 9.5,
  misssileAttached_X: -25,
  misssileAttached_Y: 6,
  main_gun_fire_X: 60,
  main_gun_fire_y: 8,
  origin_X: 40,
  origin_Y: 300,
  name_menu_x: 470,
  menu_selection_weapons: 2,
  menu_selection_speed: 2,
  menu_selection_fuel: 0,
  menu_selection_sprite: 2,
};
