import { IPlanesConfig } from 'assets/interfaces/IPlanesConfig';

export const TUCANO: IPlanesConfig = {
  id: 'tucano',
  name: 'A29 Super Tucano',
  initial_ammo: 25,
  ammo_upgrade: 50,
  max_ammo: 200,
  initial_missile: 2,
  max_missile: 4,
  speed: 150,
  max_speed: 180,
  fuel_consuption: 5,
  fuel_effiency: 2.5,
  fly_animation: 'tucano_fly',
  engine_sound: 'propeller_engine',
  muzzleFlash_X: 18,
  muzzleFlash_Y: 5,
  misssileAttached_X: 11,
  misssileAttached_Y: 6,
  main_gun_fire_X: 40,
  origin_X: 40,
  origin_Y: 300,
  name_menu_x: 440,
  menu_selection_weapons: 0,
  menu_selection_speed: 0,
  menu_selection_fuel: 2,
  menu_selection_sprite: 0,
};
